### ISSUE TITLE
Neuralynx header read error

### ISSUE THREAD

**Issue by nmarkowitz** [NeuralEnsemble/python-neo#1100]
Hi,

I'm trying to read neuralynx (.ncs) files but I keep getting an error. 

```
from neo.io import NeuralynxIO
nlxDir = 'mydata' # Directionary containing .ncs files
reader = NeuralynxIO(dirname=nlxDir)

Traceback (most recent call last):
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-871ff3d292cc>", line 5, in <module>
    nlx = NeuralynxIO(dirname=dname) # dirname=dname, filename=fname1
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\io\neuralynxio.py", line 58, in __init__
    BaseFromRaw.__init__(self, dirname)
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\io\basefromrawio.py", line 74, in __init__
    self.parse_header()
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\rawio\baserawio.py", line 185, in parse_header
    self._parse_header()
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\rawio\neuralynxrawio\neuralynxrawio.py", line 185, in _parse_header
    info = NlxHeader(filename)
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\rawio\neuralynxrawio\nlxheader.py", line 166, in __init__
```

I've tried this on both a Windows and Mac computer and have come up with the same error. Any idea what could be causing this?

**Comment by samuelgarcia** [comment]
Hi Thanks for report.
Have you tried with current master or an updated version ?
@JuliaSprenger : this is for you ?

**Comment by JuliaSprenger** [comment]
Hi @sportnoah14,
based on your traceback I assume you get the error `'Number of channel ids does not match channel names.'`.  How many ncs files do you have? Did you try already loading only a subset?

**Comment by sportnoah14** [comment]
@JuliaSprenger I reinstalled the latest version of neo using pip. I ran the following

```
from neo.io import NeuralynxIO
import os
import glob
nlxDir = 'mydata' # Directionary containing .ncs files
ncsFiles = glob.glob(nlxDir + os.sep + '*.ncs')
reader = NeuralynxIO(filename=ncsFiles[0])

Traceback (most recent call last):
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-c0562903cdb8>", line 6, in <module>
    reader = NeuralynxIO(filename=ncsFiles[0]) # dirname=dname, filename=fname1
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\io\neuralynxio.py", line 56, in __init__
    BaseFromRaw.__init__(self, filename)
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\io\basefromrawio.py", line 74, in __init__
    self.parse_header()
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\rawio\baserawio.py", line 185, in parse_header
    self._parse_header()
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\rawio\neuralynxrawio\neuralynxrawio.py", line 185, in _parse_header
    info = NlxHeader(filename)
  File "C:\Users\nmarkowitz\.conda\envs\ieeg2\lib\site-packages\neo\rawio\neuralynxrawio\nlxheader.py", line 166, in __init__
    'Number of channel ids does not match channel names.'
AssertionError: Number of channel ids does not match channel names.
```

HOWEVER, when I tried this exact same function on my mac I got a different error:
```
<insert here>
```

Any ideas? Both computers are running a conda environment using python 3.7.12 and packages installed for each are similar if not identical.

**Comment by JuliaSprenger** [comment]
The different errors on the os could be caused by `glob` returning the files in different orders. In any case can you try to identify if only a subset of your files is causing the issue by loading only a subset?

**Comment by sportnoah14** [comment]
@JuliaSprenger looped through each file in the folder to see if I could open that individual .ncs file. All of them returned an error and I wasn't able to successfully open a single one. Also, you were correct about `glob`.

**Comment by JuliaSprenger** [comment]
Can you provide one file for each of the error types you observe? If you want you can upload them here https://amubox.univ-amu.fr/s/5Cd2BedrfJs9BQf

**Comment by sportnoah14** [comment]
@JuliaSprenger sorry for the delay, I uploaded two .ncs files to the link you provided. Each file has a different error when I try to read them using `reader = NeuralynxIO(filename=<this_file>)`. Thank you for the help.

**Comment by dneophytou** [comment]
Sorry to be join this conversation, but I am having a similar issue. Has this been resolved?

**Comment by JuliaSprenger** [comment]
Hi @sportnoah14
Thanks for providing the files.
I fixed the reading of the header in https://github.com/NeuralEnsemble/python-neo/pull/1107 Can you confirm this is also working on your side? I noticed that the two files you provided have a lot of inconsistent data block durations (+-1 sample). This leads to the generation of a number of segments when reading those files. Are you aware of that issue or did you fix this already in your recording system?

**Comment by sportnoah14** [comment]
@JuliaSprenger I cloned and tried that branch. It works on individual files. However I'm still getting an error if I try to read the whole directory:

```
from neo.io import NeuralynxIO
nlxDir = 'mydata' # Directionary containing .ncs files
reader = NeuralynxIO(dirname=nlxDir)

Traceback (most recent call last):
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-7f30552bcfa2>", line 2, in <cell line: 2>
    reader = NeuralynxIO(dirname=nlxDir)
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg38/lib/python3.8/site-packages/neo/io/neuralynxio.py", line 58, in __init__
    BaseFromRaw.__init__(self, dirname)
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg38/lib/python3.8/site-packages/neo/io/basefromrawio.py", line 74, in __init__
    self.parse_header()
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg38/lib/python3.8/site-packages/neo/rawio/baserawio.py", line 185, in parse_header
    self._parse_header()
  File "/Users/sportsnoah14/opt/miniconda3/envs/ieeg38/lib/python3.8/site-packages/neo/rawio/neuralynxrawio/neuralynxrawio.py", line 287, in _parse_header
    assert sampling_rate.size == 1
AssertionError
```

Any idea what could be causing this? 

This is actually data from another group so I'll pass that info about block size to them. Thanks for catching it. Would it help if I upload the entire directory of files?

Thanks again for working on this.

**Comment by JuliaSprenger** [comment]
The `sampling_rate.size == 1` error is raised because we are still assuming all ncs files are recorded with the same sampling rate (single stream). I am currently working this to extend this for multiple streams here: https://github.com/NeuralEnsemble/python-neo/pull/1041.

**Comment by sportnoah14** [comment]
Thanks @JuliaSprenger . Let me know if I can help with this in any way. In the meantime, I can read individual streams by specifying "filename" correct?

**Comment by JuliaSprenger** [comment]
@sportnoah14 Would it be possible to add the two test files you provided to the public database of test files for Neo on [gin](https://gin.g-node.org/Neuralensemble/ephy_testing_data)? If yes, whom can I reference as provider?

**Comment by JuliaSprenger** [comment]
For testing purposes I created a branch containing the header changes (https://github.com/NeuralEnsemble/python-neo/pull/1107) as well as streams (https://github.com/NeuralEnsemble/python-neo/pull/1041). This branch can be found here: https://github.com/JuliaSprenger/python-neo/tree/enh/add/neuralynx_header_rate This branch should work at least for sessions that don't have inconsistent data block durations / timestamps. @sportnoah14 Could you test this on your side with some clean sessions?

**Comment by sportnoah14** [comment]
@JuliaSprenger, for using those files I sent you as test data, I've e-mailed those that originally sent it to me as test data to assist them. I'll relay their response to you when I hear back from them.

**Comment by JuliaSprenger** [comment]
Thanks! If it helps, I would only include the file header and the first 32 (2)  packets of the files, so only a small fraction of the file you provided.
