### ISSUE TITLE
[NixIO] saving/loading looses the links between analogsignals and channel_indexes

### ISSUE THREAD

**Issue by rgutzen** [NeuralEnsemble/python-neo#766]
Minimal example:
neo v0.8.0
nixio v1.5.0b1

```
import neo
import quantities as pq
import numpy as np
import itertools

# create dummy objects
asig = neo.AnalogSignal(np.arange(3),
                        units='mV',
                        sampling_rate=1000*pq.Hz)
chidx = neo.ChannelIndex(name='Electrode array', 
                         index=np.arange(3))

# create links
asig.channel_index = chidx
chidx.analogsignals = [asig]

# build neo structure
blk = neo.Block()
seg = neo.Segment()
seg.analogsignals.append(asig)
blk.channel_indexes.append(chidx)
blk.segments.append(seg)

# check links
print('Pre-nixify:')
print(blk.channel_indexes[0].analogsignals)
print(blk.segments[0].analogsignals[0].channel_index)

# write/read
with neo.NixIO('temp.nix') as io:
    io.write(blk)
with neo.NixIO('temp.nix') as io:
    loaded_blk = io.read_block()

# check links
print('Post-nixify:')
print(loaded_blk.channel_indexes[0].analogsignals)
print(loaded_blk.segments[0].analogsignals[0].channel_index)
```

Output:
```
>> Pre-nixify:
>> [<AnalogSignal(array([[0], [1], [2]]) * mV, [0.0 s, 0.003 s], sampling rate: 1000.0 Hz)>]
>> <neo.core.channelindex.ChannelIndex object at 0x7fcd1fe17cc0>
>> Post-nixify:
>> []
>> None
```

**Comment by achilleas-k** [comment]
I can partially confirm this.  I get the following output, with the same lib versions you specified:
```
Neo version: 0.8.0
NIX version: v1.5.0b1
Pre-nixify:
[<AnalogSignal(array([[0],
       [1],
       [2]]) * mV, [0.0 s, 0.003 s], sampling rate: 1000.0 Hz)>]
<neo.core.channelindex.ChannelIndex object at 0x7f845129f3d0>
Post-nixify:
[<AnalogSignal(array([[0],
       [1],
       [2]]) * mV, [0.0 s, 0.003 s], sampling rate: 1000.0 Hz)>]
None
```

ChannelIndex -> AnalogSignal link is preserved, but the inverse isn't.

**Comment by achilleas-k** [comment]
I think I got it.  The `create_many_to_one_relationship()` and `create_many_to_many_relationship()` utility methods should fix this.  I knew these existed but they weren't being called.  Not sure how I neglected that.

Can you try the following patch (on current Neo master 82b9600973f0ed092bbb13f2b5880a0c5e55ec04) and tell me if it works for you?
```patch
diff --git a/neo/io/nixio.py b/neo/io/nixio.py
index 1b4835ec..c04df431 100644
--- a/neo/io/nixio.py
+++ b/neo/io/nixio.py
@@ -291,6 +291,10 @@ class NixIO(BaseIO):
             # parent reference
             newchx.block = neo_block
 
+        # create object links
+        neo_block.create_many_to_one_relationship()
+        neo_block.create_many_to_many_relationship()
+
         # reset maps
         self._neo_map = dict()
         self._ref_map = dict()
```

**Comment by rgutzen** [comment]
Also with the patch, both links are still lost.
I also double-checked whether the channelindex -> analogsignal link is preserved with a new environment (python 3.7.3), but I still get the same result.
Here the full environment:
```
certifi==2019.9.11
h5py==2.10.0
neo==0.8.0
nixio==1.5.0b1
numpy==1.17.4
pkginfo==1.5.0.1
quantities==0.12.3
readme-renderer==24.0
requests-toolbelt==0.9.1
six==1.13.0
tqdm==4.35.0
twine==1.13.0
```

**Comment by achilleas-k** [comment]
I'm still not sure why you're not getting the ChannelIndex -> AnalogSignal link.  I went as far as creating a Docker container to test this (see below).

When I build and run it, I get [the output I pasted above](https://github.com/NeuralEnsemble/python-neo/issues/766#issuecomment-553860010).  Uncommenting the two lines where it installs the [fix/nixio-channel-links](https://github.com/G-Node/python-neo@fix/nixio-channel-links) branch fixes it.

I can't imagine where the difference is.

```Dockerfile
FROM ubuntu:bionic

RUN apt-get update
RUN apt-get install -y python3.7 python3-pip

RUN mkdir nixiobug
WORKDIR nixiobug

# https://github.com/NeuralEnsemble/python-neo/issues/766#issue-522800484 -> example.py
# https://github.com/NeuralEnsemble/python-neo/issues/766#issuecomment-553900436 -> robin.deps
COPY robin.deps .
COPY example.py .

RUN python3.7 --version
RUN python3.7 -m pip install -r robin.deps
RUN python3.7 -m pip list

# Uncomment to build with patched NIXIO
# RUN apt-get install -y git
# RUN python3.7 -m pip install --upgrade git+https://github.com/G-Node/python-neo@fix/nixio-channel-links  # includes patch from https://github.com/NeuralEnsemble/python-neo/issues/766#issuecomment-553863102

ENTRYPOINT ["python3.7", "example.py"]
```

**Comment by rgutzen** [comment]
Thank you for the fix!
I now figured out why it didn't work for me. I didn't manually delete the temp.nix file, and `io.write(blk)` doesn't overwrite the file. Thus, I can now confirm that the patch works!

**Comment by achilleas-k** [comment]
Didn't even consider that.  Thanks for putting my mind at ease :)

**Comment by apdavison** [comment]
Closed by #767
